name: valuable_workspace
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^7.4.0
workspace:
  - packages/valuable/example
  - packages/valuable
melos: 
  sdkPath: .fvm/flutter_sdk
  packages:
    - packages/**
  command:
    bootstrap:
      usePubspecOverrides: false

    version:
      branch: master